"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import {
  GitFork,
  ArrowLeft,
  Copy,
  Download,
  CheckCircle,
  HelpCircle,
  Loader2,
  Flame,
  Shield,
} from "lucide-react";
import { toast } from "sonner";
import { SessionData } from "@/lib/types";
import Link from "next/link";

export default function VerdictPage() {
  const params = useParams();
  const sessionId = params.id as string;

  const [session, setSession] = useState<SessionData | null>(null);
  const [loading, setLoading] = useState(true);
  const [userDecision, setUserDecision] = useState("");
  const [userReason, setUserReason] = useState("");

  useEffect(() => {
    async function loadVerdict() {
      try {
        // First try to load existing session
        const getRes = await fetch(`/api/session/${sessionId}`);
        const getData = await getRes.json();
        if (getRes.ok && getData.session?.verdict) {
          setSession(getData.session);
          setLoading(false);
          return;
        }

        // Only synthesize if no verdict exists yet
        const res = await fetch("/api/session/synthesize", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ sessionId }),
        });
        const data = await res.json();
        if (res.ok) {
          setSession(data);
        } else {
          toast.error(data.error || "Failed to load verdict");
        }
      } catch {
        toast.error("Failed to load verdict");
      } finally {
        setLoading(false);
      }
    }
    loadVerdict();
  }, [sessionId]);

  function generateMarkdown(): string {
    if (!session?.verdict) return "";
    const v = session.verdict;
    return `# Parallel You — Decision Report
**Decision:** ${session.decision}
**Date:** ${new Date(session.createdAt).toLocaleDateString()}

## Risk-Taker's Best Points
${v.bestPointsA.map((p) => `- ${p}`).join("\n")}

## Pragmatist's Best Points
${v.bestPointsB.map((p) => `- ${p}`).join("\n")}

## Shared Facts
${v.sharedFacts.map((p) => `- ${p}`).join("\n")}

## Open Questions
${v.openQuestions.map((p) => `- ${p}`).join("\n")}

## Recommended Next Step
${v.recommendedNextStep}

${userDecision ? `## My Decision\n${userDecision}\n\n**Reason:** ${userReason}` : ""}

---
*Generated by Parallel You. This is a thinking tool, not professional advice.*
`;
  }

  function copyToClipboard() {
    navigator.clipboard.writeText(generateMarkdown());
    toast.success("Copied to clipboard");
  }

  function downloadMarkdown() {
    const blob = new Blob([generateMarkdown()], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `parallel-you-${sessionId}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Downloaded");
  }

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="flex items-center gap-2 text-muted-foreground">
          <Loader2 className="h-5 w-5 animate-spin" />
          Synthesizing verdict...
        </div>
      </div>
    );
  }

  if (!session?.verdict) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center space-y-2">
          <p className="text-muted-foreground">No verdict available</p>
          <Link href={`/session/${sessionId}`}>
            <Button variant="outline" size="sm">Back to debate</Button>
          </Link>
        </div>
      </div>
    );
  }

  const v = session.verdict;

  return (
    <div className="min-h-screen flex flex-col">
      <nav className="flex items-center gap-2 px-6 py-4 border-b border-border/50">
        <Link href={`/session/${sessionId}`} className="text-muted-foreground hover:text-foreground">
          <ArrowLeft className="h-4 w-4" />
        </Link>
        <GitFork className="h-5 w-5 text-primary" />
        <span className="font-semibold">Verdict</span>
      </nav>

      <main className="flex-1 max-w-2xl mx-auto w-full p-6 space-y-6">
        <div className="text-center space-y-1">
          <h1 className="text-2xl font-bold">Your Debate Verdict</h1>
          <p className="text-sm text-muted-foreground">{session.decision}</p>
        </div>

        {/* Best points A */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Flame className="h-4 w-4 text-orange-400" />
              Risk-Taker&apos;s Best Points
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-1.5">
              {v.bestPointsA.map((p, i) => (
                <li key={i} className="text-sm flex items-start gap-2">
                  <span className="text-orange-400 mt-0.5">-</span>
                  {p}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        {/* Best points B */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <Shield className="h-4 w-4 text-cyan-500" />
              Pragmatist&apos;s Best Points
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-1.5">
              {v.bestPointsB.map((p, i) => (
                <li key={i} className="text-sm flex items-start gap-2">
                  <span className="text-cyan-500 mt-0.5">-</span>
                  {p}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        {/* Shared facts */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <CheckCircle className="h-4 w-4 text-green-500" />
              Shared Facts
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {v.sharedFacts.map((f, i) => (
                <Badge key={i} variant="secondary">{f}</Badge>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Open questions */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm flex items-center gap-2">
              <HelpCircle className="h-4 w-4 text-purple-500" />
              Open Questions
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-1.5">
              {v.openQuestions.map((q, i) => (
                <li key={i} className="text-sm text-muted-foreground">{q}</li>
              ))}
            </ul>
          </CardContent>
        </Card>

        {/* Recommended next step */}
        <Card className="border-primary/30">
          <CardContent className="pt-4">
            <p className="text-sm font-medium mb-1">Recommended Next Step</p>
            <p className="text-sm text-muted-foreground">{v.recommendedNextStep}</p>
          </CardContent>
        </Card>

        <Separator />

        {/* My decision */}
        <div className="space-y-3">
          <h2 className="text-lg font-semibold">My Decision</h2>
          <div className="space-y-1.5">
            <Label>What did you decide?</Label>
            <Textarea
              placeholder="I decided to..."
              value={userDecision}
              onChange={(e) => setUserDecision(e.target.value)}
              rows={2}
            />
          </div>
          <div className="space-y-1.5">
            <Label>Why?</Label>
            <Textarea
              placeholder="Because..."
              value={userReason}
              onChange={(e) => setUserReason(e.target.value)}
              rows={2}
            />
          </div>
        </div>

        {/* Export */}
        <div className="flex gap-2">
          <Button variant="outline" onClick={copyToClipboard} className="gap-1">
            <Copy className="h-4 w-4" /> Copy
          </Button>
          <Button variant="outline" onClick={downloadMarkdown} className="gap-1">
            <Download className="h-4 w-4" /> Download .md
          </Button>
        </div>

        <p className="text-[10px] text-muted-foreground text-center">
          Disclaimer: Parallel You is a thinking tool. It does not provide medical, legal, or financial advice.
        </p>
      </main>
    </div>
  );
}
